/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // 'transparent': 'transparent',
        // 'current': 'currentColor',
        // 'black': '#000',
        // 'white': '#fff',
        // 'gray-50': '#f9fafb',
        // 'gray-100': '#f4f5f7',
        // 'gray-200': '#e5e7eb',
        // 'gray-300': '#d2d6dc',
        // 'gray-400': '#9fa6b2',
        // 'gray-500': '#6b7280',
        // 'gray-600': '#4b5563',
        // 'gray-700': '#374151',
        // 'gray-800': '#1f2937',
        // 'gray-900': '#111827',
        // 'red-50': '#fef2f2',
        // 'red-100': '#fee2e2',
        // 'red-200': '#fecaca',
        // 'red-300': '#fca5a5',
        // 'red-400': '#f87171',
        // 'red-500': '#ef4444',
        // 'red-600': '#dc2626',
        // 'red-700': '#b91c1c',
        // 'red-800': '#991b1b',
        // 'red-900': '#7f1d1d',
        // 'yellow-50': '#fffbeb',
        // 'yellow-100': '#fef3c7',
        // 'yellow-200': '#fde68a',
        // 'yellow-300': '#fcd34d',
        // 'yellow-400': '#fbbf24',
        // 'yellow-500': '#f59e0b',
        // 'yellow-600': '#d97706',
        // 'yellow-700': '#b45309',
        // 'yellow-800': '#92400e',
        // 'yellow-900': '#78350f',
        // 'green-50': '#ecfdf5',
        // 'green-100': '#d1fae5',
        // 'green-200': '#a7f3d0',
        // 'green-300': '#6ee7b7',
        // 'green-400': '#34d399',
        // 'green-500': '#10b981',
        // 'green-600': '#059669',
        // 'green-700': '#047857',
        // 'green-800': '#065f46',
        // 'green-900': '#064e3b',
        // 'blue-50': '#eff6ff',
        // 'blue-100': '#dbeafe',
        // 'blue-200': '#bfdbfe',
        // 'blue-300': '#93c5fd',
        // 'blue-400': '#60a5fa',
        // 'blue-500': '#3b82f6',
        // 'blue-600': '#2563eb',
        // 'blue-700': '#1d4ed8',
        // 'blue-800': '#1e40af',
        // 'blue-900': '#1e3a8a',
        // 'indigo-50': '#eef2ff',
        // 'indigo-100': '#e0e7ff',
        // 'indigo-200': '#c7d2fe',
        // 'indigo-300': '#a5b4fc',
        // 'indigo-400': '#818cf8',
        // 'indigo-500': '#6366f1',
        // 'indigo-600': '#4f46e5',
        // 'indigo-700': '#4338ca',
        // 'indigo-800': '#3730a3',
        // 'indigo-900': '#312e81',
        // 'purple-50': '#f5f3ff',
        // 'purple-100': '#ede9fe',
        // 'purple-200': '#ddd6fe',
        // 'purple-300': '#c4b5fd',
        // 'purple-400': '#a78bfa',
        // 'purple-500': '#8b5cf6',
        // 'purple-600': '#7c3aed',
        // 'purple-700': '#6d28d9',
        // 'purple-800': '#5b21b6',
        // 'purple-900': '#4c1d95',
        // 'pink-50': '#fdf2f8',
        // 'pink-100': '#fce7f3',
        // 'pink-200': '#fbcfe8',
        // 'pink-300': '#f9a8d4',
        // 'pink-400': '#f472b6',
        // 'pink-500': '#ec4899',
        // 'pink-600': '#db2777',
        // 'pink-700': '#be185d',
        // 'pink-800': '#9d174d',
        // 'pink-900': '#831843',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}